name: e_commerce_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images
flutter_assets:
  assets_path: assets/images/ # Path to your assets directory
  output_path: lib/core/utils # Where the generated Dart file will be saved
  filename: app_images.dart # Name of the generated Dart file
  field_prefix: # Prefix for the generated fields (e.g., `correctLogo` for an image named `logo.png`)
    null
flutter_intl:
  enabled: true
