// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLXNCNodgoodJqkS3Wwc-tSTGsZXAkPvo',
    appId: '1:306262733084:web:16dab69f43dc3803628ad9',
    messagingSenderId: '306262733084',
    projectId: 'e-commerce-fruit-hub',
    authDomain: 'e-commerce-fruit-hub.firebaseapp.com',
    storageBucket: 'e-commerce-fruit-hub.firebasestorage.app',
    measurementId: 'G-JF3JJM0PK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCavU7aTFhc_M-dWzw-HRZ02vPGLZvk1OA',
    appId: '1:306262733084:android:8425a75007b795fe628ad9',
    messagingSenderId: '306262733084',
    projectId: 'e-commerce-fruit-hub',
    storageBucket: 'e-commerce-fruit-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWdx97kET2TmKlNRQEQo1eOuWUPqnb-yk',
    appId: '1:306262733084:ios:c2c2c47e1ed26316628ad9',
    messagingSenderId: '306262733084',
    projectId: 'e-commerce-fruit-hub',
    storageBucket: 'e-commerce-fruit-hub.firebasestorage.app',
    androidClientId: '306262733084-ql2q8rqg6rc8fr8luqpssohl1g9kn8ge.apps.googleusercontent.com',
    iosClientId: '306262733084-5otorte0p7iatph0bnmag3psuh87i1ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWdx97kET2TmKlNRQEQo1eOuWUPqnb-yk',
    appId: '1:306262733084:ios:c2c2c47e1ed26316628ad9',
    messagingSenderId: '306262733084',
    projectId: 'e-commerce-fruit-hub',
    storageBucket: 'e-commerce-fruit-hub.firebasestorage.app',
    androidClientId: '306262733084-ql2q8rqg6rc8fr8luqpssohl1g9kn8ge.apps.googleusercontent.com',
    iosClientId: '306262733084-5otorte0p7iatph0bnmag3psuh87i1ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLXNCNodgoodJqkS3Wwc-tSTGsZXAkPvo',
    appId: '1:306262733084:web:c68cfc93200d033f628ad9',
    messagingSenderId: '306262733084',
    projectId: 'e-commerce-fruit-hub',
    authDomain: 'e-commerce-fruit-hub.firebaseapp.com',
    storageBucket: 'e-commerce-fruit-hub.firebasestorage.app',
    measurementId: 'G-GF89Y28WP5',
  );
}
